import { Sidebar, SidebarProvider } from "@/components/layout/Sidebar/sidebar";
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import { Header } from '../components/layout';
import { SidebarContent } from '../components/layout/Sidebar/SidebarContent';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='fr'>
				<head />
			<body>
	
				{/* Fond jungle en absolute/fixed */}
				<div className='fixed inset-0 -z-10 bg-black'>
					<Image
						src='/fond_jungle.png'
						alt='Jungle futuriste'
						fill
						className='object-cover opacity-80'
						draggable={true}
						priority
					/>
					<div />
				</div>
				<SidebarProvider>
					<Header />
					<Sidebar>
						<SidebarContent />
					</Sidebar>
					{children}
				</SidebarProvider>
      </body>
	</html>
  );
}
